// <auto-generated />
namespace Wedding.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207082032386_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN0Z227bNvR9wP5B0NM2oJaTIUUb2C1SJxmCLhfEbvdoMNKxQ4yiNJEK7G/bwz5pv7BDXWiJlGTJSbB1bxbJc78f//3nX5OPm5A5T5AIGvGpezQauw5wPwooX0/dVK7evHM/fvj+u8lFEG6cr+W7Y/UOIbmYuo9SxqeeJ/xHCIkYhdRPIhGt5MiPQo8EkXc8Hr/zjsYeIAoXcTnO5D7lkoaQfeDnLOI+xDIl7DoKgIniHG/mGVbnhoQgYuLD1P0NAsXcKH/pOmeMEuRiDmw1kKXxe8WSq4khuQtkS24X2xgyklP3LhKy+gLffIZt7QCP7pIohkRu72FVgbsKXMerw3omsAY14BQLU/eKy5+PXecmZYw8MDxYESbAdeK3p3MZJfALcEiIhOCOSAkJGuYqgEyEQhWn8dt+2njvjY+VNjzCeSSJRCtbzBusLqhkUHI6lwkaxXUu6QaCX4Gv5aPm9ppsypOjMfrNF07RwRBIJik0SNdNVmkI/UWinAOJ48/nEv8SB0rdJeFz/FigHw/HIyBRvwZKcDJcezfkia4ze5rmI2uMnntg2aV4pHEeRCO8WCol4+1lEoX3Ectf54fLBUnWoFQfmTfzKE18g4OJtwupzkBDNIfEGYIdEmYF2DcQZQd4yfHJy3lJ4QjD3aR0BttNSgfq4yZnQkQ+zUjvLFeQrUtwwQOnlYdcewXXqKuUSRoz6iPFqfuTpY0mXNrtd7iy2tCNbOJVJLD9X+UxQtG7CuE+sWid5baNWXTy93OQdbvstFbjyZKnDpyHvgWb6cYArbBfgy9NX7m3/MKM3i4TaRZL7rw+0KVRKtAFX2ZCqMvR4HnaFLvew8ubj7JJ8Vq6lMk1iWOMy0rXUpw487xlmb2ZD29NwhyH54uGDkVzqylhoiJrMG6RNHJ6SRMhsVSRB6JCfxaE1rMejldSqvqfbaPSpcrX6ncOUe/bRnZjVdXcJQoTYo7N5ALDvDZY1igSRpKWbmoWsTTkXZ1ZF5ai0akiKY7646h1LSY7+qI/Pt2IVHHpwwF4dCNSQ6RPbUwTz7CR6QSe5QVGLJou1cvhsqzwDH+z+osMwT53a4Rq9ZO8qaj5SVN70oXDtsW/ZYd6xrSMURaALoWXbxq02hTHKsXbKq0XClsNA0yxbDGHUoWmPISpov70ZKotGy3bUlI7X2ZBsy1o1TXzifYfXd+MOjYpasr+kdwqMvkT10Hen2igCsx8KySEI/VgNP+DzRjNEl754JpwugIhF9HvoNYLWAMPn+x1ly1EwP7L4z1VKtg7YgwcLWtjOX8iif9IEnsIf/7UXeL+ISSbH587SasP+RKTdKPEJ/sE/hbG1Ffxlr2qU8Pki6nu0HDryt3NwdmSU3upfGmr/YBoWTbE+kGK7JiBG6tifVLaN/0eWVX4lp8DAwnOmZ+PdTMifBLYQqvq1EE5H0Xr1HuMzGo7DCtIlEMThjlHyAQLmNXe3CWU+zQmrCKrXYh7hqKSRiM0b84hBq4CzJCtJ7X2rkMjNvS6T/7WrUKXqzT1KhWDWdZqMtX/xll626+9NXsVd9nTDr64wzSvoeylwf5lVOsuKu8FscI/RGjgPPv13VK1LamacDZtrxpQtvCqb1pQN3LcvRzTu62OHVnLWGOmcGMi3bMcq4pYm7f6b8X2C1eu3rqEax6PrKRjrndeX7wBSz97CMJwq/x7ieEu6HqHQv2XycGvBZp+c8VXURn0BkflE6OTuAZJsDcmZ4mkK+JLvPZBiOxvgK+EpfjkInyA4IrfpjJOJYoM4QPbVpWh8kYX/WyzWed5chtn6/6XEAHZpKq9v+WfUsoCzfdlQwvUgkIlpKLpVbaUqvldbzWmm4j3RFSoT+fRBYQxQ2Tils/JE7Tztl+HdY1NzilZJySsajA/KTiZE6RcIYEEqhA7eviJ7hqEmw//AGpM40ivHwAA"; }
        }
    }
}
